### ISSUE TITLE
"No module named mwclient"

### ISSUE THREAD

**Issue by bmarcinek** [aquach/vim-mediawiki-editor#2]
Hey! Awesome plugin, but I can't seem to get it to work. No matter what I do, I get the error in the title.

Installed mwclient via pip, Vim is compiled with python,  installed vim-mediawiki-editor via vundle, got the error.

Thought it was maybe because mwclient was installed via sudo, uninstalled mwclient, uninstalled vim-mediawiki-editor; reinstalled mwclient for my user, reinstalled vim-mediawiki-editor, still getting the issue.

Any tips?

**Comment by bmarcinek** [comment]
So it seems to be a Python 2.7 - 3.4 issue.  I copied the installed mwclient files (as well as 'six' and 'requests', two other dependencies) from /usr/lib/python3.4 to /usr/lib/python2.7.  That solved the "no module found" issue.... but now I'm getting an invalid JSON response when I try to connect to my personal wiki.  I think this is an issue with my wiki's config and how mwclient talks to it (all is gravy with en.wikipedia.org). I will check over at mwclient for proper config of my wiki.  Again, awesome plugin, thanks for everything :D

**Comment by danmichaelo** [comment]
From https://github.com/mwclient/mwclient/issues/94 it seems like the problem was a wrong mediawiki path. In order to configure the path, I guess vim-mediawiki-editor needs a `g:mediawiki_editor_path` option.

_(About the Python 3 issue: Python 3.x support has been added to the development version of mwclient and a stable release will hopefully be released soon)_

**Comment by aquach** [comment]
The invalid JSON response issue is fixed by #3, I believe.
